GL_LinkGroupBegin(base,GL_ES_VERSION_2_0)
  GL_Link_core(glAttachShader, "glAttachShader",  void (APIENTRYP )(GLuint,GLuint),  void (APIENTRYP glAttachShader)(GLuint program, GLuint shader))
  GL_Link_core(glBindAttribLocation, "glBindAttribLocation",  void (APIENTRYP )(GLuint,GLuint,const  GLchar *),  void (APIENTRYP glBindAttribLocation)(GLuint program, GLuint index, const  GLchar * name))
  GL_Link_core(glBindFramebuffer, "glBindFramebuffer",  void (APIENTRYP )(GLenum,GLuint),  void (APIENTRYP glBindFramebuffer)(GLenum target, GLuint framebuffer))
  GL_Link_core(glBindRenderbuffer, "glBindRenderbuffer",  void (APIENTRYP )(GLenum,GLuint),  void (APIENTRYP glBindRenderbuffer)(GLenum target, GLuint renderbuffer))
  GL_Link_core(glBlendColor, "glBlendColor",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glBlendColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
  GL_Link_core(glBlendEquation, "glBlendEquation",  void (APIENTRYP )(GLenum),  void (APIENTRYP glBlendEquation)(GLenum mode))
  GL_Link_core(glBlendEquationSeparate, "glBlendEquationSeparate",  void (APIENTRYP )(GLenum,GLenum),  void (APIENTRYP glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha))
  GL_Link_core(glBlendFuncSeparate, "glBlendFuncSeparate",  void (APIENTRYP )(GLenum,GLenum,GLenum,GLenum),  void (APIENTRYP glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha))
  GL_Link_core(glCheckFramebufferStatus, "glCheckFramebufferStatus", GLenum (APIENTRYP )(GLenum), GLenum (APIENTRYP glCheckFramebufferStatus)(GLenum target))
  GL_Link_core(glCompileShader, "glCompileShader",  void (APIENTRYP )(GLuint),  void (APIENTRYP glCompileShader)(GLuint shader))
  GL_Link_core(glCreateProgram, "glCreateProgram", GLuint (APIENTRYP )(), GLuint (APIENTRYP glCreateProgram)())
  GL_Link_core(glCreateShader, "glCreateShader", GLuint (APIENTRYP )(GLenum), GLuint (APIENTRYP glCreateShader)(GLenum type))
  GL_Link_core(glDeleteFramebuffers, "glDeleteFramebuffers",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteFramebuffers)(GLsizei n, const  GLuint * framebuffers))
  GL_Link_core(glDeleteProgram, "glDeleteProgram",  void (APIENTRYP )(GLuint),  void (APIENTRYP glDeleteProgram)(GLuint program))
  GL_Link_core(glDeleteRenderbuffers, "glDeleteRenderbuffers",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteRenderbuffers)(GLsizei n, const  GLuint * renderbuffers))
  GL_Link_core(glDeleteShader, "glDeleteShader",  void (APIENTRYP )(GLuint),  void (APIENTRYP glDeleteShader)(GLuint shader))
  GL_Link_core(glDetachShader, "glDetachShader",  void (APIENTRYP )(GLuint,GLuint),  void (APIENTRYP glDetachShader)(GLuint program, GLuint shader))
  GL_Link_core(glDisableVertexAttribArray, "glDisableVertexAttribArray",  void (APIENTRYP )(GLuint),  void (APIENTRYP glDisableVertexAttribArray)(GLuint index))
  GL_Link_core(glEnableVertexAttribArray, "glEnableVertexAttribArray",  void (APIENTRYP )(GLuint),  void (APIENTRYP glEnableVertexAttribArray)(GLuint index))
  GL_Link_core(glFramebufferRenderbuffer, "glFramebufferRenderbuffer",  void (APIENTRYP )(GLenum,GLenum,GLenum,GLuint),  void (APIENTRYP glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer))
  GL_Link_core(glFramebufferTexture2D, "glFramebufferTexture2D",  void (APIENTRYP )(GLenum,GLenum,GLenum,GLuint,GLint),  void (APIENTRYP glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level))
  GL_Link_core(glGenFramebuffers, "glGenFramebuffers",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenFramebuffers)(GLsizei n, GLuint * framebuffers))
  GL_Link_core(glGenRenderbuffers, "glGenRenderbuffers",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenRenderbuffers)(GLsizei n, GLuint * renderbuffers))
  GL_Link_core(glGenerateMipmap, "glGenerateMipmap",  void (APIENTRYP )(GLenum),  void (APIENTRYP glGenerateMipmap)(GLenum target))
  GL_Link_core(glGetActiveAttrib, "glGetActiveAttrib",  void (APIENTRYP )(GLuint,GLuint,GLsizei,GLsizei *,GLint *,GLenum *,GLchar *),  void (APIENTRYP glGetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name))
  GL_Link_core(glGetActiveUniform, "glGetActiveUniform",  void (APIENTRYP )(GLuint,GLuint,GLsizei,GLsizei *,GLint *,GLenum *,GLchar *),  void (APIENTRYP glGetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name))
  GL_Link_core(glGetAttachedShaders, "glGetAttachedShaders",  void (APIENTRYP )(GLuint,GLsizei,GLsizei *,GLuint *),  void (APIENTRYP glGetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei * count, GLuint * shaders))
  GL_Link_core(glGetAttribLocation, "glGetAttribLocation", GLint (APIENTRYP )(GLuint,const  GLchar *), GLint (APIENTRYP glGetAttribLocation)(GLuint program, const  GLchar * name))
  GL_Link_core(glGetFramebufferAttachmentParameteriv, "glGetFramebufferAttachmentParameteriv",  void (APIENTRYP )(GLenum,GLenum,GLenum,GLint *),  void (APIENTRYP glGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint * params))
  GL_Link_core(glGetProgramInfoLog, "glGetProgramInfoLog",  void (APIENTRYP )(GLuint,GLsizei,GLsizei *,GLchar *),  void (APIENTRYP glGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog))
  GL_Link_core(glGetProgramiv, "glGetProgramiv",  void (APIENTRYP )(GLuint,GLenum,GLint *),  void (APIENTRYP glGetProgramiv)(GLuint program, GLenum pname, GLint * params))
  GL_Link_core(glGetRenderbufferParameteriv, "glGetRenderbufferParameteriv",  void (APIENTRYP )(GLenum,GLenum,GLint *),  void (APIENTRYP glGetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint * params))
  GL_Link_core(glGetShaderInfoLog, "glGetShaderInfoLog",  void (APIENTRYP )(GLuint,GLsizei,GLsizei *,GLchar *),  void (APIENTRYP glGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog))
  GL_Link_core(glGetShaderPrecisionFormat, "glGetShaderPrecisionFormat",  void (APIENTRYP )(GLenum,GLenum,GLint *,GLint *),  void (APIENTRYP glGetShaderPrecisionFormat)(GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision))
  GL_Link_core(glGetShaderSource, "glGetShaderSource",  void (APIENTRYP )(GLuint,GLsizei,GLsizei *,GLchar *),  void (APIENTRYP glGetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * source))
  GL_Link_core(glGetShaderiv, "glGetShaderiv",  void (APIENTRYP )(GLuint,GLenum,GLint *),  void (APIENTRYP glGetShaderiv)(GLuint shader, GLenum pname, GLint * params))
  GL_Link_core(glGetUniformLocation, "glGetUniformLocation", GLint (APIENTRYP )(GLuint,const  GLchar *), GLint (APIENTRYP glGetUniformLocation)(GLuint program, const  GLchar * name))
  GL_Link_core(glGetUniformfv, "glGetUniformfv",  void (APIENTRYP )(GLuint,GLint,GLfloat *),  void (APIENTRYP glGetUniformfv)(GLuint program, GLint location, GLfloat * params))
  GL_Link_core(glGetUniformiv, "glGetUniformiv",  void (APIENTRYP )(GLuint,GLint,GLint *),  void (APIENTRYP glGetUniformiv)(GLuint program, GLint location, GLint * params))
  GL_Link_core(glGetVertexAttribPointerv, "glGetVertexAttribPointerv",  void (APIENTRYP )(GLuint,GLenum, void **),  void (APIENTRYP glGetVertexAttribPointerv)(GLuint index, GLenum pname,  void ** pointer))
  GL_Link_core(glGetVertexAttribfv, "glGetVertexAttribfv",  void (APIENTRYP )(GLuint,GLenum,GLfloat *),  void (APIENTRYP glGetVertexAttribfv)(GLuint index, GLenum pname, GLfloat * params))
  GL_Link_core(glGetVertexAttribiv, "glGetVertexAttribiv",  void (APIENTRYP )(GLuint,GLenum,GLint *),  void (APIENTRYP glGetVertexAttribiv)(GLuint index, GLenum pname, GLint * params))
  GL_Link_core(glIsFramebuffer, "glIsFramebuffer", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsFramebuffer)(GLuint framebuffer))
  GL_Link_core(glIsProgram, "glIsProgram", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsProgram)(GLuint program))
  GL_Link_core(glIsRenderbuffer, "glIsRenderbuffer", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsRenderbuffer)(GLuint renderbuffer))
  GL_Link_core(glIsShader, "glIsShader", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsShader)(GLuint shader))
  GL_Link_core(glLinkProgram, "glLinkProgram",  void (APIENTRYP )(GLuint),  void (APIENTRYP glLinkProgram)(GLuint program))
  GL_Link_core(glReleaseShaderCompiler, "glReleaseShaderCompiler",  void (APIENTRYP )(),  void (APIENTRYP glReleaseShaderCompiler)())
  GL_Link_core(glRenderbufferStorage, "glRenderbufferStorage",  void (APIENTRYP )(GLenum,GLenum,GLsizei,GLsizei),  void (APIENTRYP glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height))
  GL_Link_core(glShaderBinary, "glShaderBinary",  void (APIENTRYP )(GLsizei,const  GLuint *,GLenum, const void *,GLsizei),  void (APIENTRYP glShaderBinary)(GLsizei count, const  GLuint * shaders, GLenum binaryformat,  const void * binary, GLsizei length))
  GL_Link_core(glShaderSource, "glShaderSource",  void (APIENTRYP )(GLuint,GLsizei,const  GLchar *const*,const  GLint *),  void (APIENTRYP glShaderSource)(GLuint shader, GLsizei count, const  GLchar *const* string, const  GLint * length))
  GL_Link_core(glStencilFuncSeparate, "glStencilFuncSeparate",  void (APIENTRYP )(GLenum,GLenum,GLint,GLuint),  void (APIENTRYP glStencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask))
  GL_Link_core(glStencilMaskSeparate, "glStencilMaskSeparate",  void (APIENTRYP )(GLenum,GLuint),  void (APIENTRYP glStencilMaskSeparate)(GLenum face, GLuint mask))
  GL_Link_core(glStencilOpSeparate, "glStencilOpSeparate",  void (APIENTRYP )(GLenum,GLenum,GLenum,GLenum),  void (APIENTRYP glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass))
  GL_Link_core(glUniform1f, "glUniform1f",  void (APIENTRYP )(GLint,GLfloat),  void (APIENTRYP glUniform1f)(GLint location, GLfloat v0))
  GL_Link_core(glUniform1fv, "glUniform1fv",  void (APIENTRYP )(GLint,GLsizei,const  GLfloat *),  void (APIENTRYP glUniform1fv)(GLint location, GLsizei count, const  GLfloat * value))
  GL_Link_core(glUniform1i, "glUniform1i",  void (APIENTRYP )(GLint,GLint),  void (APIENTRYP glUniform1i)(GLint location, GLint v0))
  GL_Link_core(glUniform1iv, "glUniform1iv",  void (APIENTRYP )(GLint,GLsizei,const  GLint *),  void (APIENTRYP glUniform1iv)(GLint location, GLsizei count, const  GLint * value))
  GL_Link_core(glUniform2f, "glUniform2f",  void (APIENTRYP )(GLint,GLfloat,GLfloat),  void (APIENTRYP glUniform2f)(GLint location, GLfloat v0, GLfloat v1))
  GL_Link_core(glUniform2fv, "glUniform2fv",  void (APIENTRYP )(GLint,GLsizei,const  GLfloat *),  void (APIENTRYP glUniform2fv)(GLint location, GLsizei count, const  GLfloat * value))
  GL_Link_core(glUniform2i, "glUniform2i",  void (APIENTRYP )(GLint,GLint,GLint),  void (APIENTRYP glUniform2i)(GLint location, GLint v0, GLint v1))
  GL_Link_core(glUniform2iv, "glUniform2iv",  void (APIENTRYP )(GLint,GLsizei,const  GLint *),  void (APIENTRYP glUniform2iv)(GLint location, GLsizei count, const  GLint * value))
  GL_Link_core(glUniform3f, "glUniform3f",  void (APIENTRYP )(GLint,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2))
  GL_Link_core(glUniform3fv, "glUniform3fv",  void (APIENTRYP )(GLint,GLsizei,const  GLfloat *),  void (APIENTRYP glUniform3fv)(GLint location, GLsizei count, const  GLfloat * value))
  GL_Link_core(glUniform3i, "glUniform3i",  void (APIENTRYP )(GLint,GLint,GLint,GLint),  void (APIENTRYP glUniform3i)(GLint location, GLint v0, GLint v1, GLint v2))
  GL_Link_core(glUniform3iv, "glUniform3iv",  void (APIENTRYP )(GLint,GLsizei,const  GLint *),  void (APIENTRYP glUniform3iv)(GLint location, GLsizei count, const  GLint * value))
  GL_Link_core(glUniform4f, "glUniform4f",  void (APIENTRYP )(GLint,GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3))
  GL_Link_core(glUniform4fv, "glUniform4fv",  void (APIENTRYP )(GLint,GLsizei,const  GLfloat *),  void (APIENTRYP glUniform4fv)(GLint location, GLsizei count, const  GLfloat * value))
  GL_Link_core(glUniform4i, "glUniform4i",  void (APIENTRYP )(GLint,GLint,GLint,GLint,GLint),  void (APIENTRYP glUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3))
  GL_Link_core(glUniform4iv, "glUniform4iv",  void (APIENTRYP )(GLint,GLsizei,const  GLint *),  void (APIENTRYP glUniform4iv)(GLint location, GLsizei count, const  GLint * value))
  GL_Link_core(glUniformMatrix2fv, "glUniformMatrix2fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUniformMatrix3fv, "glUniformMatrix3fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUniformMatrix4fv, "glUniformMatrix4fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUseProgram, "glUseProgram",  void (APIENTRYP )(GLuint),  void (APIENTRYP glUseProgram)(GLuint program))
  GL_Link_core(glValidateProgram, "glValidateProgram",  void (APIENTRYP )(GLuint),  void (APIENTRYP glValidateProgram)(GLuint program))
  GL_Link_core(glVertexAttrib1f, "glVertexAttrib1f",  void (APIENTRYP )(GLuint,GLfloat),  void (APIENTRYP glVertexAttrib1f)(GLuint index, GLfloat x))
  GL_Link_core(glVertexAttrib1fv, "glVertexAttrib1fv",  void (APIENTRYP )(GLuint,const  GLfloat *),  void (APIENTRYP glVertexAttrib1fv)(GLuint index, const  GLfloat * v))
  GL_Link_core(glVertexAttrib2f, "glVertexAttrib2f",  void (APIENTRYP )(GLuint,GLfloat,GLfloat),  void (APIENTRYP glVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y))
  GL_Link_core(glVertexAttrib2fv, "glVertexAttrib2fv",  void (APIENTRYP )(GLuint,const  GLfloat *),  void (APIENTRYP glVertexAttrib2fv)(GLuint index, const  GLfloat * v))
  GL_Link_core(glVertexAttrib3f, "glVertexAttrib3f",  void (APIENTRYP )(GLuint,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z))
  GL_Link_core(glVertexAttrib3fv, "glVertexAttrib3fv",  void (APIENTRYP )(GLuint,const  GLfloat *),  void (APIENTRYP glVertexAttrib3fv)(GLuint index, const  GLfloat * v))
  GL_Link_core(glVertexAttrib4f, "glVertexAttrib4f",  void (APIENTRYP )(GLuint,GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
  GL_Link_core(glVertexAttrib4fv, "glVertexAttrib4fv",  void (APIENTRYP )(GLuint,const  GLfloat *),  void (APIENTRYP glVertexAttrib4fv)(GLuint index, const  GLfloat * v))
  GL_Link_core(glVertexAttribPointer, "glVertexAttribPointer",  void (APIENTRYP )(GLuint,GLint,GLenum,GLboolean,GLsizei, const void *),  void (APIENTRYP glVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride,  const void * pointer))
GL_LinkGroupEnd(base,GL_ES_VERSION_2_0)
GL_LinkGroupBegin(base,GL_ES_VERSION_3_0)
  GL_Link_core(glBeginQuery, "glBeginQuery",  void (APIENTRYP )(GLenum,GLuint),  void (APIENTRYP glBeginQuery)(GLenum target, GLuint id))
  GL_Link_core(glBeginTransformFeedback, "glBeginTransformFeedback",  void (APIENTRYP )(GLenum),  void (APIENTRYP glBeginTransformFeedback)(GLenum primitiveMode))
  GL_Link_core(glBindBufferBase, "glBindBufferBase",  void (APIENTRYP )(GLenum,GLuint,GLuint),  void (APIENTRYP glBindBufferBase)(GLenum target, GLuint index, GLuint buffer))
  GL_Link_core(glBindBufferRange, "glBindBufferRange",  void (APIENTRYP )(GLenum,GLuint,GLuint,GLintptr,GLsizeiptr),  void (APIENTRYP glBindBufferRange)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size))
  GL_Link_core(glBindSampler, "glBindSampler",  void (APIENTRYP )(GLuint,GLuint),  void (APIENTRYP glBindSampler)(GLuint unit, GLuint sampler))
  GL_Link_core(glBindTransformFeedback, "glBindTransformFeedback",  void (APIENTRYP )(GLenum,GLuint),  void (APIENTRYP glBindTransformFeedback)(GLenum target, GLuint id))
  GL_Link_core(glBindVertexArray, "glBindVertexArray",  void (APIENTRYP )(GLuint),  void (APIENTRYP glBindVertexArray)(GLuint array))
  GL_Link_core(glBlitFramebuffer, "glBlitFramebuffer",  void (APIENTRYP )(GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLint,GLbitfield,GLenum),  void (APIENTRYP glBlitFramebuffer)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter))
  GL_Link_core(glClearBufferfi, "glClearBufferfi",  void (APIENTRYP )(GLenum,GLint,GLfloat,GLint),  void (APIENTRYP glClearBufferfi)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil))
  GL_Link_core(glClearBufferfv, "glClearBufferfv",  void (APIENTRYP )(GLenum,GLint,const  GLfloat *),  void (APIENTRYP glClearBufferfv)(GLenum buffer, GLint drawbuffer, const  GLfloat * value))
  GL_Link_core(glClearBufferiv, "glClearBufferiv",  void (APIENTRYP )(GLenum,GLint,const  GLint *),  void (APIENTRYP glClearBufferiv)(GLenum buffer, GLint drawbuffer, const  GLint * value))
  GL_Link_core(glClearBufferuiv, "glClearBufferuiv",  void (APIENTRYP )(GLenum,GLint,const  GLuint *),  void (APIENTRYP glClearBufferuiv)(GLenum buffer, GLint drawbuffer, const  GLuint * value))
  GL_Link_core(glClientWaitSync, "glClientWaitSync", GLenum (APIENTRYP )(GLsync,GLbitfield,GLuint64), GLenum (APIENTRYP glClientWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout))
  GL_Link_core(glCompressedTexImage3D, "glCompressedTexImage3D",  void (APIENTRYP )(GLenum,GLint,GLenum,GLsizei,GLsizei,GLsizei,GLint,GLsizei, const void *),  void (APIENTRYP glCompressedTexImage3D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize,  const void * data))
  GL_Link_core(glCompressedTexSubImage3D, "glCompressedTexSubImage3D",  void (APIENTRYP )(GLenum,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLsizei, const void *),  void (APIENTRYP glCompressedTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize,  const void * data))
  GL_Link_core(glCopyBufferSubData, "glCopyBufferSubData",  void (APIENTRYP )(GLenum,GLenum,GLintptr,GLintptr,GLsizeiptr),  void (APIENTRYP glCopyBufferSubData)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size))
  GL_Link_core(glCopyTexSubImage3D, "glCopyTexSubImage3D",  void (APIENTRYP )(GLenum,GLint,GLint,GLint,GLint,GLint,GLint,GLsizei,GLsizei),  void (APIENTRYP glCopyTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height))
  GL_Link_core(glDeleteQueries, "glDeleteQueries",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteQueries)(GLsizei n, const  GLuint * ids))
  GL_Link_core(glDeleteSamplers, "glDeleteSamplers",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteSamplers)(GLsizei count, const  GLuint * samplers))
  GL_Link_core(glDeleteSync, "glDeleteSync",  void (APIENTRYP )(GLsync),  void (APIENTRYP glDeleteSync)(GLsync sync))
  GL_Link_core(glDeleteTransformFeedbacks, "glDeleteTransformFeedbacks",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteTransformFeedbacks)(GLsizei n, const  GLuint * ids))
  GL_Link_core(glDeleteVertexArrays, "glDeleteVertexArrays",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteVertexArrays)(GLsizei n, const  GLuint * arrays))
  GL_Link_core(glDrawArraysInstanced, "glDrawArraysInstanced",  void (APIENTRYP )(GLenum,GLint,GLsizei,GLsizei),  void (APIENTRYP glDrawArraysInstanced)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount))
  GL_Link_core(glDrawBuffers, "glDrawBuffers",  void (APIENTRYP )(GLsizei,const  GLenum *),  void (APIENTRYP glDrawBuffers)(GLsizei n, const  GLenum * bufs))
  GL_Link_core(glDrawElementsInstanced, "glDrawElementsInstanced",  void (APIENTRYP )(GLenum,GLsizei,GLenum, const void *,GLsizei),  void (APIENTRYP glDrawElementsInstanced)(GLenum mode, GLsizei count, GLenum type,  const void * indices, GLsizei instancecount))
  GL_Link_core(glDrawRangeElements, "glDrawRangeElements",  void (APIENTRYP )(GLenum,GLuint,GLuint,GLsizei,GLenum, const void *),  void (APIENTRYP glDrawRangeElements)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type,  const void * indices))
  GL_Link_core(glEndQuery, "glEndQuery",  void (APIENTRYP )(GLenum),  void (APIENTRYP glEndQuery)(GLenum target))
  GL_Link_core(glEndTransformFeedback, "glEndTransformFeedback",  void (APIENTRYP )(),  void (APIENTRYP glEndTransformFeedback)())
  GL_Link_core(glFenceSync, "glFenceSync", GLsync (APIENTRYP )(GLenum,GLbitfield), GLsync (APIENTRYP glFenceSync)(GLenum condition, GLbitfield flags))
  GL_Link_core(glFlushMappedBufferRange, "glFlushMappedBufferRange",  void (APIENTRYP )(GLenum,GLintptr,GLsizeiptr),  void (APIENTRYP glFlushMappedBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length))
  GL_Link_core(glFramebufferTextureLayer, "glFramebufferTextureLayer",  void (APIENTRYP )(GLenum,GLenum,GLuint,GLint,GLint),  void (APIENTRYP glFramebufferTextureLayer)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer))
  GL_Link_core(glGenQueries, "glGenQueries",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenQueries)(GLsizei n, GLuint * ids))
  GL_Link_core(glGenSamplers, "glGenSamplers",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenSamplers)(GLsizei count, GLuint * samplers))
  GL_Link_core(glGenTransformFeedbacks, "glGenTransformFeedbacks",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenTransformFeedbacks)(GLsizei n, GLuint * ids))
  GL_Link_core(glGenVertexArrays, "glGenVertexArrays",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenVertexArrays)(GLsizei n, GLuint * arrays))
  GL_Link_core(glGetActiveUniformBlockName, "glGetActiveUniformBlockName",  void (APIENTRYP )(GLuint,GLuint,GLsizei,GLsizei *,GLchar *),  void (APIENTRYP glGetActiveUniformBlockName)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformBlockName))
  GL_Link_core(glGetActiveUniformBlockiv, "glGetActiveUniformBlockiv",  void (APIENTRYP )(GLuint,GLuint,GLenum,GLint *),  void (APIENTRYP glGetActiveUniformBlockiv)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint * params))
  GL_Link_core(glGetActiveUniformsiv, "glGetActiveUniformsiv",  void (APIENTRYP )(GLuint,GLsizei,const  GLuint *,GLenum,GLint *),  void (APIENTRYP glGetActiveUniformsiv)(GLuint program, GLsizei uniformCount, const  GLuint * uniformIndices, GLenum pname, GLint * params))
  GL_Link_core(glGetBufferParameteri64v, "glGetBufferParameteri64v",  void (APIENTRYP )(GLenum,GLenum,GLint64 *),  void (APIENTRYP glGetBufferParameteri64v)(GLenum target, GLenum pname, GLint64 * params))
  GL_Link_core(glGetBufferPointerv, "glGetBufferPointerv",  void (APIENTRYP )(GLenum,GLenum, void **),  void (APIENTRYP glGetBufferPointerv)(GLenum target, GLenum pname,  void ** params))
  GL_Link_core(glGetFragDataLocation, "glGetFragDataLocation", GLint (APIENTRYP )(GLuint,const  GLchar *), GLint (APIENTRYP glGetFragDataLocation)(GLuint program, const  GLchar * name))
  GL_Link_core(glGetInteger64i_v, "glGetInteger64i_v",  void (APIENTRYP )(GLenum,GLuint,GLint64 *),  void (APIENTRYP glGetInteger64i_v)(GLenum target, GLuint index, GLint64 * data))
  GL_Link_core(glGetInteger64v, "glGetInteger64v",  void (APIENTRYP )(GLenum,GLint64 *),  void (APIENTRYP glGetInteger64v)(GLenum pname, GLint64 * data))
  GL_Link_core(glGetIntegeri_v, "glGetIntegeri_v",  void (APIENTRYP )(GLenum,GLuint,GLint *),  void (APIENTRYP glGetIntegeri_v)(GLenum target, GLuint index, GLint * data))
  GL_Link_core(glGetInternalformativ, "glGetInternalformativ",  void (APIENTRYP )(GLenum,GLenum,GLenum,GLsizei,GLint *),  void (APIENTRYP glGetInternalformativ)(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint * params))
  GL_Link_core(glGetProgramBinary, "glGetProgramBinary",  void (APIENTRYP )(GLuint,GLsizei,GLsizei *,GLenum *, void *),  void (APIENTRYP glGetProgramBinary)(GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat,  void * binary))
  GL_Link_core(glGetQueryObjectuiv, "glGetQueryObjectuiv",  void (APIENTRYP )(GLuint,GLenum,GLuint *),  void (APIENTRYP glGetQueryObjectuiv)(GLuint id, GLenum pname, GLuint * params))
  GL_Link_core(glGetQueryiv, "glGetQueryiv",  void (APIENTRYP )(GLenum,GLenum,GLint *),  void (APIENTRYP glGetQueryiv)(GLenum target, GLenum pname, GLint * params))
  GL_Link_core(glGetSamplerParameterfv, "glGetSamplerParameterfv",  void (APIENTRYP )(GLuint,GLenum,GLfloat *),  void (APIENTRYP glGetSamplerParameterfv)(GLuint sampler, GLenum pname, GLfloat * params))
  GL_Link_core(glGetSamplerParameteriv, "glGetSamplerParameteriv",  void (APIENTRYP )(GLuint,GLenum,GLint *),  void (APIENTRYP glGetSamplerParameteriv)(GLuint sampler, GLenum pname, GLint * params))
  GL_Link_core(glGetStringi, "glGetStringi", const  GLubyte * (APIENTRYP )(GLenum,GLuint), const  GLubyte * (APIENTRYP glGetStringi)(GLenum name, GLuint index))
  GL_Link_core(glGetSynciv, "glGetSynciv",  void (APIENTRYP )(GLsync,GLenum,GLsizei,GLsizei *,GLint *),  void (APIENTRYP glGetSynciv)(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei * length, GLint * values))
  GL_Link_core(glGetTransformFeedbackVarying, "glGetTransformFeedbackVarying",  void (APIENTRYP )(GLuint,GLuint,GLsizei,GLsizei *,GLsizei *,GLenum *,GLchar *),  void (APIENTRYP glGetTransformFeedbackVarying)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLsizei * size, GLenum * type, GLchar * name))
  GL_Link_core(glGetUniformBlockIndex, "glGetUniformBlockIndex", GLuint (APIENTRYP )(GLuint,const  GLchar *), GLuint (APIENTRYP glGetUniformBlockIndex)(GLuint program, const  GLchar * uniformBlockName))
  GL_Link_core(glGetUniformIndices, "glGetUniformIndices",  void (APIENTRYP )(GLuint,GLsizei,const  GLchar *const*,GLuint *),  void (APIENTRYP glGetUniformIndices)(GLuint program, GLsizei uniformCount, const  GLchar *const* uniformNames, GLuint * uniformIndices))
  GL_Link_core(glGetUniformuiv, "glGetUniformuiv",  void (APIENTRYP )(GLuint,GLint,GLuint *),  void (APIENTRYP glGetUniformuiv)(GLuint program, GLint location, GLuint * params))
  GL_Link_core(glGetVertexAttribIiv, "glGetVertexAttribIiv",  void (APIENTRYP )(GLuint,GLenum,GLint *),  void (APIENTRYP glGetVertexAttribIiv)(GLuint index, GLenum pname, GLint * params))
  GL_Link_core(glGetVertexAttribIuiv, "glGetVertexAttribIuiv",  void (APIENTRYP )(GLuint,GLenum,GLuint *),  void (APIENTRYP glGetVertexAttribIuiv)(GLuint index, GLenum pname, GLuint * params))
  GL_Link_core(glInvalidateFramebuffer, "glInvalidateFramebuffer",  void (APIENTRYP )(GLenum,GLsizei,const  GLenum *),  void (APIENTRYP glInvalidateFramebuffer)(GLenum target, GLsizei numAttachments, const  GLenum * attachments))
  GL_Link_core(glInvalidateSubFramebuffer, "glInvalidateSubFramebuffer",  void (APIENTRYP )(GLenum,GLsizei,const  GLenum *,GLint,GLint,GLsizei,GLsizei),  void (APIENTRYP glInvalidateSubFramebuffer)(GLenum target, GLsizei numAttachments, const  GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height))
  GL_Link_core(glIsQuery, "glIsQuery", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsQuery)(GLuint id))
  GL_Link_core(glIsSampler, "glIsSampler", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsSampler)(GLuint sampler))
  GL_Link_core(glIsSync, "glIsSync", GLboolean (APIENTRYP )(GLsync), GLboolean (APIENTRYP glIsSync)(GLsync sync))
  GL_Link_core(glIsTransformFeedback, "glIsTransformFeedback", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsTransformFeedback)(GLuint id))
  GL_Link_core(glIsVertexArray, "glIsVertexArray", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsVertexArray)(GLuint array))
  GL_Link_core(glMapBufferRange, "glMapBufferRange",  void * (APIENTRYP )(GLenum,GLintptr,GLsizeiptr,GLbitfield),  void * (APIENTRYP glMapBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access))
  GL_Link_core(glPauseTransformFeedback, "glPauseTransformFeedback",  void (APIENTRYP )(),  void (APIENTRYP glPauseTransformFeedback)())
  GL_Link_core(glProgramBinary, "glProgramBinary",  void (APIENTRYP )(GLuint,GLenum, const void *,GLsizei),  void (APIENTRYP glProgramBinary)(GLuint program, GLenum binaryFormat,  const void * binary, GLsizei length))
  GL_Link_core(glProgramParameteri, "glProgramParameteri",  void (APIENTRYP )(GLuint,GLenum,GLint),  void (APIENTRYP glProgramParameteri)(GLuint program, GLenum pname, GLint value))
  GL_Link_core(glReadBuffer, "glReadBuffer",  void (APIENTRYP )(GLenum),  void (APIENTRYP glReadBuffer)(GLenum mode))
  GL_Link_core(glRenderbufferStorageMultisample, "glRenderbufferStorageMultisample",  void (APIENTRYP )(GLenum,GLsizei,GLenum,GLsizei,GLsizei),  void (APIENTRYP glRenderbufferStorageMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height))
  GL_Link_core(glResumeTransformFeedback, "glResumeTransformFeedback",  void (APIENTRYP )(),  void (APIENTRYP glResumeTransformFeedback)())
  GL_Link_core(glSamplerParameterf, "glSamplerParameterf",  void (APIENTRYP )(GLuint,GLenum,GLfloat),  void (APIENTRYP glSamplerParameterf)(GLuint sampler, GLenum pname, GLfloat param))
  GL_Link_core(glSamplerParameterfv, "glSamplerParameterfv",  void (APIENTRYP )(GLuint,GLenum,const  GLfloat *),  void (APIENTRYP glSamplerParameterfv)(GLuint sampler, GLenum pname, const  GLfloat * param))
  GL_Link_core(glSamplerParameteri, "glSamplerParameteri",  void (APIENTRYP )(GLuint,GLenum,GLint),  void (APIENTRYP glSamplerParameteri)(GLuint sampler, GLenum pname, GLint param))
  GL_Link_core(glSamplerParameteriv, "glSamplerParameteriv",  void (APIENTRYP )(GLuint,GLenum,const  GLint *),  void (APIENTRYP glSamplerParameteriv)(GLuint sampler, GLenum pname, const  GLint * param))
  GL_Link_core(glTexImage3D, "glTexImage3D",  void (APIENTRYP )(GLenum,GLint,GLint,GLsizei,GLsizei,GLsizei,GLint,GLenum,GLenum, const void *),  void (APIENTRYP glTexImage3D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type,  const void * pixels))
  GL_Link_core(glTexStorage2D, "glTexStorage2D",  void (APIENTRYP )(GLenum,GLsizei,GLenum,GLsizei,GLsizei),  void (APIENTRYP glTexStorage2D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height))
  GL_Link_core(glTexStorage3D, "glTexStorage3D",  void (APIENTRYP )(GLenum,GLsizei,GLenum,GLsizei,GLsizei,GLsizei),  void (APIENTRYP glTexStorage3D)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth))
  GL_Link_core(glTexSubImage3D, "glTexSubImage3D",  void (APIENTRYP )(GLenum,GLint,GLint,GLint,GLint,GLsizei,GLsizei,GLsizei,GLenum,GLenum, const void *),  void (APIENTRYP glTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type,  const void * pixels))
  GL_Link_core(glTransformFeedbackVaryings, "glTransformFeedbackVaryings",  void (APIENTRYP )(GLuint,GLsizei,const  GLchar *const*,GLenum),  void (APIENTRYP glTransformFeedbackVaryings)(GLuint program, GLsizei count, const  GLchar *const* varyings, GLenum bufferMode))
  GL_Link_core(glUniform1ui, "glUniform1ui",  void (APIENTRYP )(GLint,GLuint),  void (APIENTRYP glUniform1ui)(GLint location, GLuint v0))
  GL_Link_core(glUniform1uiv, "glUniform1uiv",  void (APIENTRYP )(GLint,GLsizei,const  GLuint *),  void (APIENTRYP glUniform1uiv)(GLint location, GLsizei count, const  GLuint * value))
  GL_Link_core(glUniform2ui, "glUniform2ui",  void (APIENTRYP )(GLint,GLuint,GLuint),  void (APIENTRYP glUniform2ui)(GLint location, GLuint v0, GLuint v1))
  GL_Link_core(glUniform2uiv, "glUniform2uiv",  void (APIENTRYP )(GLint,GLsizei,const  GLuint *),  void (APIENTRYP glUniform2uiv)(GLint location, GLsizei count, const  GLuint * value))
  GL_Link_core(glUniform3ui, "glUniform3ui",  void (APIENTRYP )(GLint,GLuint,GLuint,GLuint),  void (APIENTRYP glUniform3ui)(GLint location, GLuint v0, GLuint v1, GLuint v2))
  GL_Link_core(glUniform3uiv, "glUniform3uiv",  void (APIENTRYP )(GLint,GLsizei,const  GLuint *),  void (APIENTRYP glUniform3uiv)(GLint location, GLsizei count, const  GLuint * value))
  GL_Link_core(glUniform4ui, "glUniform4ui",  void (APIENTRYP )(GLint,GLuint,GLuint,GLuint,GLuint),  void (APIENTRYP glUniform4ui)(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3))
  GL_Link_core(glUniform4uiv, "glUniform4uiv",  void (APIENTRYP )(GLint,GLsizei,const  GLuint *),  void (APIENTRYP glUniform4uiv)(GLint location, GLsizei count, const  GLuint * value))
  GL_Link_core(glUniformBlockBinding, "glUniformBlockBinding",  void (APIENTRYP )(GLuint,GLuint,GLuint),  void (APIENTRYP glUniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding))
  GL_Link_core(glUniformMatrix2x3fv, "glUniformMatrix2x3fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix2x3fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUniformMatrix2x4fv, "glUniformMatrix2x4fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix2x4fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUniformMatrix3x2fv, "glUniformMatrix3x2fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix3x2fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUniformMatrix3x4fv, "glUniformMatrix3x4fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix3x4fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUniformMatrix4x2fv, "glUniformMatrix4x2fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix4x2fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUniformMatrix4x3fv, "glUniformMatrix4x3fv",  void (APIENTRYP )(GLint,GLsizei,GLboolean,const  GLfloat *),  void (APIENTRYP glUniformMatrix4x3fv)(GLint location, GLsizei count, GLboolean transpose, const  GLfloat * value))
  GL_Link_core(glUnmapBuffer, "glUnmapBuffer", GLboolean (APIENTRYP )(GLenum), GLboolean (APIENTRYP glUnmapBuffer)(GLenum target))
  GL_Link_core(glVertexAttribDivisor, "glVertexAttribDivisor",  void (APIENTRYP )(GLuint,GLuint),  void (APIENTRYP glVertexAttribDivisor)(GLuint index, GLuint divisor))
  GL_Link_core(glVertexAttribI4i, "glVertexAttribI4i",  void (APIENTRYP )(GLuint,GLint,GLint,GLint,GLint),  void (APIENTRYP glVertexAttribI4i)(GLuint index, GLint x, GLint y, GLint z, GLint w))
  GL_Link_core(glVertexAttribI4iv, "glVertexAttribI4iv",  void (APIENTRYP )(GLuint,const  GLint *),  void (APIENTRYP glVertexAttribI4iv)(GLuint index, const  GLint * v))
  GL_Link_core(glVertexAttribI4ui, "glVertexAttribI4ui",  void (APIENTRYP )(GLuint,GLuint,GLuint,GLuint,GLuint),  void (APIENTRYP glVertexAttribI4ui)(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w))
  GL_Link_core(glVertexAttribI4uiv, "glVertexAttribI4uiv",  void (APIENTRYP )(GLuint,const  GLuint *),  void (APIENTRYP glVertexAttribI4uiv)(GLuint index, const  GLuint * v))
  GL_Link_core(glVertexAttribIPointer, "glVertexAttribIPointer",  void (APIENTRYP )(GLuint,GLint,GLenum,GLsizei, const void *),  void (APIENTRYP glVertexAttribIPointer)(GLuint index, GLint size, GLenum type, GLsizei stride,  const void * pointer))
  GL_Link_core(glWaitSync, "glWaitSync",  void (APIENTRYP )(GLsync,GLbitfield,GLuint64),  void (APIENTRYP glWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout))
GL_LinkGroupEnd(base,GL_ES_VERSION_3_0)
GL_LinkGroupBegin(base,GL_VERSION_ES_CM_1_0)
  GL_Link_core(glActiveTexture, "glActiveTexture",  void (APIENTRYP )(GLenum),  void (APIENTRYP glActiveTexture)(GLenum texture))
  GL_Link_compat(glAlphaFunc, "glAlphaFunc",  void (APIENTRYP )(GLenum,GLfloat),  void (APIENTRYP glAlphaFunc)(GLenum func, GLfloat ref))
  GL_Link_core(glAlphaFuncx, "glAlphaFuncx",  void (APIENTRYP )(GLenum,GLfixed),  void (APIENTRYP glAlphaFuncx)(GLenum func, GLfixed ref))
  GL_Link_core(glBindBuffer, "glBindBuffer",  void (APIENTRYP )(GLenum,GLuint),  void (APIENTRYP glBindBuffer)(GLenum target, GLuint buffer))
  GL_Link_core(glBindTexture, "glBindTexture",  void (APIENTRYP )(GLenum,GLuint),  void (APIENTRYP glBindTexture)(GLenum target, GLuint texture))
  GL_Link_core(glBlendFunc, "glBlendFunc",  void (APIENTRYP )(GLenum,GLenum),  void (APIENTRYP glBlendFunc)(GLenum sfactor, GLenum dfactor))
  GL_Link_core(glBufferData, "glBufferData",  void (APIENTRYP )(GLenum,GLsizeiptr, const void *,GLenum),  void (APIENTRYP glBufferData)(GLenum target, GLsizeiptr size,  const void * data, GLenum usage))
  GL_Link_core(glBufferSubData, "glBufferSubData",  void (APIENTRYP )(GLenum,GLintptr,GLsizeiptr, const void *),  void (APIENTRYP glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size,  const void * data))
  GL_Link_core(glClear, "glClear",  void (APIENTRYP )(GLbitfield),  void (APIENTRYP glClear)(GLbitfield mask))
  GL_Link_core(glClearColor, "glClearColor",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
  GL_Link_core(glClearColorx, "glClearColorx",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed,GLfixed),  void (APIENTRYP glClearColorx)(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha))
  GL_Link_core(glClearDepthf, "glClearDepthf",  void (APIENTRYP )(GLfloat),  void (APIENTRYP glClearDepthf)(GLfloat d))
  GL_Link_core(glClearDepthx, "glClearDepthx",  void (APIENTRYP )(GLfixed),  void (APIENTRYP glClearDepthx)(GLfixed depth))
  GL_Link_core(glClearStencil, "glClearStencil",  void (APIENTRYP )(GLint),  void (APIENTRYP glClearStencil)(GLint s))
  GL_Link_compat(glClientActiveTexture, "glClientActiveTexture",  void (APIENTRYP )(GLenum),  void (APIENTRYP glClientActiveTexture)(GLenum texture))
  GL_Link_core(glClipPlanef, "glClipPlanef",  void (APIENTRYP )(GLenum,const  GLfloat *),  void (APIENTRYP glClipPlanef)(GLenum p, const  GLfloat * eqn))
  GL_Link_core(glClipPlanex, "glClipPlanex",  void (APIENTRYP )(GLenum,const  GLfixed *),  void (APIENTRYP glClipPlanex)(GLenum plane, const  GLfixed * equation))
  GL_Link_compat(glColor4f, "glColor4f",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glColor4f)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
  GL_Link_compat(glColor4ub, "glColor4ub",  void (APIENTRYP )(GLubyte,GLubyte,GLubyte,GLubyte),  void (APIENTRYP glColor4ub)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
  GL_Link_core(glColor4x, "glColor4x",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed,GLfixed),  void (APIENTRYP glColor4x)(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha))
  GL_Link_core(glColorMask, "glColorMask",  void (APIENTRYP )(GLboolean,GLboolean,GLboolean,GLboolean),  void (APIENTRYP glColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
  GL_Link_compat(glColorPointer, "glColorPointer",  void (APIENTRYP )(GLint,GLenum,GLsizei, const void *),  void (APIENTRYP glColorPointer)(GLint size, GLenum type, GLsizei stride,  const void * pointer))
  GL_Link_core(glCompressedTexImage2D, "glCompressedTexImage2D",  void (APIENTRYP )(GLenum,GLint,GLenum,GLsizei,GLsizei,GLint,GLsizei, const void *),  void (APIENTRYP glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize,  const void * data))
  GL_Link_core(glCompressedTexSubImage2D, "glCompressedTexSubImage2D",  void (APIENTRYP )(GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLsizei, const void *),  void (APIENTRYP glCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize,  const void * data))
  GL_Link_core(glCopyTexImage2D, "glCopyTexImage2D",  void (APIENTRYP )(GLenum,GLint,GLenum,GLint,GLint,GLsizei,GLsizei,GLint),  void (APIENTRYP glCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
  GL_Link_core(glCopyTexSubImage2D, "glCopyTexSubImage2D",  void (APIENTRYP )(GLenum,GLint,GLint,GLint,GLint,GLint,GLsizei,GLsizei),  void (APIENTRYP glCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
  GL_Link_core(glCullFace, "glCullFace",  void (APIENTRYP )(GLenum),  void (APIENTRYP glCullFace)(GLenum mode))
  GL_Link_core(glDeleteBuffers, "glDeleteBuffers",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteBuffers)(GLsizei n, const  GLuint * buffers))
  GL_Link_core(glDeleteTextures, "glDeleteTextures",  void (APIENTRYP )(GLsizei,const  GLuint *),  void (APIENTRYP glDeleteTextures)(GLsizei n, const  GLuint * textures))
  GL_Link_core(glDepthFunc, "glDepthFunc",  void (APIENTRYP )(GLenum),  void (APIENTRYP glDepthFunc)(GLenum func))
  GL_Link_core(glDepthMask, "glDepthMask",  void (APIENTRYP )(GLboolean),  void (APIENTRYP glDepthMask)(GLboolean flag))
  GL_Link_core(glDepthRangef, "glDepthRangef",  void (APIENTRYP )(GLfloat,GLfloat),  void (APIENTRYP glDepthRangef)(GLfloat n, GLfloat f))
  GL_Link_core(glDepthRangex, "glDepthRangex",  void (APIENTRYP )(GLfixed,GLfixed),  void (APIENTRYP glDepthRangex)(GLfixed n, GLfixed f))
  GL_Link_core(glDisable, "glDisable",  void (APIENTRYP )(GLenum),  void (APIENTRYP glDisable)(GLenum cap))
  GL_Link_compat(glDisableClientState, "glDisableClientState",  void (APIENTRYP )(GLenum),  void (APIENTRYP glDisableClientState)(GLenum array))
  GL_Link_core(glDrawArrays, "glDrawArrays",  void (APIENTRYP )(GLenum,GLint,GLsizei),  void (APIENTRYP glDrawArrays)(GLenum mode, GLint first, GLsizei count))
  GL_Link_core(glDrawElements, "glDrawElements",  void (APIENTRYP )(GLenum,GLsizei,GLenum, const void *),  void (APIENTRYP glDrawElements)(GLenum mode, GLsizei count, GLenum type,  const void * indices))
  GL_Link_core(glEnable, "glEnable",  void (APIENTRYP )(GLenum),  void (APIENTRYP glEnable)(GLenum cap))
  GL_Link_compat(glEnableClientState, "glEnableClientState",  void (APIENTRYP )(GLenum),  void (APIENTRYP glEnableClientState)(GLenum array))
  GL_Link_core(glFinish, "glFinish",  void (APIENTRYP )(),  void (APIENTRYP glFinish)())
  GL_Link_core(glFlush, "glFlush",  void (APIENTRYP )(),  void (APIENTRYP glFlush)())
  GL_Link_compat(glFogf, "glFogf",  void (APIENTRYP )(GLenum,GLfloat),  void (APIENTRYP glFogf)(GLenum pname, GLfloat param))
  GL_Link_compat(glFogfv, "glFogfv",  void (APIENTRYP )(GLenum,const  GLfloat *),  void (APIENTRYP glFogfv)(GLenum pname, const  GLfloat * params))
  GL_Link_core(glFogx, "glFogx",  void (APIENTRYP )(GLenum,GLfixed),  void (APIENTRYP glFogx)(GLenum pname, GLfixed param))
  GL_Link_core(glFogxv, "glFogxv",  void (APIENTRYP )(GLenum,const  GLfixed *),  void (APIENTRYP glFogxv)(GLenum pname, const  GLfixed * param))
  GL_Link_core(glFrontFace, "glFrontFace",  void (APIENTRYP )(GLenum),  void (APIENTRYP glFrontFace)(GLenum mode))
  GL_Link_core(glFrustumf, "glFrustumf",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glFrustumf)(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f))
  GL_Link_core(glFrustumx, "glFrustumx",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed,GLfixed,GLfixed,GLfixed),  void (APIENTRYP glFrustumx)(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f))
  GL_Link_core(glGenBuffers, "glGenBuffers",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenBuffers)(GLsizei n, GLuint * buffers))
  GL_Link_core(glGenTextures, "glGenTextures",  void (APIENTRYP )(GLsizei,GLuint *),  void (APIENTRYP glGenTextures)(GLsizei n, GLuint * textures))
  GL_Link_core(glGetBooleanv, "glGetBooleanv",  void (APIENTRYP )(GLenum,GLboolean *),  void (APIENTRYP glGetBooleanv)(GLenum pname, GLboolean * data))
  GL_Link_core(glGetBufferParameteriv, "glGetBufferParameteriv",  void (APIENTRYP )(GLenum,GLenum,GLint *),  void (APIENTRYP glGetBufferParameteriv)(GLenum target, GLenum pname, GLint * params))
  GL_Link_core(glGetClipPlanef, "glGetClipPlanef",  void (APIENTRYP )(GLenum,GLfloat *),  void (APIENTRYP glGetClipPlanef)(GLenum plane, GLfloat * equation))
  GL_Link_core(glGetClipPlanex, "glGetClipPlanex",  void (APIENTRYP )(GLenum,GLfixed *),  void (APIENTRYP glGetClipPlanex)(GLenum plane, GLfixed * equation))
  GL_Link_core(glGetError, "glGetError", GLenum (APIENTRYP )(), GLenum (APIENTRYP glGetError)())
  GL_Link_core(glGetFixedv, "glGetFixedv",  void (APIENTRYP )(GLenum,GLfixed *),  void (APIENTRYP glGetFixedv)(GLenum pname, GLfixed * params))
  GL_Link_core(glGetFloatv, "glGetFloatv",  void (APIENTRYP )(GLenum,GLfloat *),  void (APIENTRYP glGetFloatv)(GLenum pname, GLfloat * data))
  GL_Link_core(glGetIntegerv, "glGetIntegerv",  void (APIENTRYP )(GLenum,GLint *),  void (APIENTRYP glGetIntegerv)(GLenum pname, GLint * data))
  GL_Link_compat(glGetLightfv, "glGetLightfv",  void (APIENTRYP )(GLenum,GLenum,GLfloat *),  void (APIENTRYP glGetLightfv)(GLenum light, GLenum pname, GLfloat * params))
  GL_Link_core(glGetLightxv, "glGetLightxv",  void (APIENTRYP )(GLenum,GLenum,GLfixed *),  void (APIENTRYP glGetLightxv)(GLenum light, GLenum pname, GLfixed * params))
  GL_Link_compat(glGetMaterialfv, "glGetMaterialfv",  void (APIENTRYP )(GLenum,GLenum,GLfloat *),  void (APIENTRYP glGetMaterialfv)(GLenum face, GLenum pname, GLfloat * params))
  GL_Link_core(glGetMaterialxv, "glGetMaterialxv",  void (APIENTRYP )(GLenum,GLenum,GLfixed *),  void (APIENTRYP glGetMaterialxv)(GLenum face, GLenum pname, GLfixed * params))
  GL_Link_core(glGetString, "glGetString", const  GLubyte * (APIENTRYP )(GLenum), const  GLubyte * (APIENTRYP glGetString)(GLenum name))
  GL_Link_compat(glGetTexEnvfv, "glGetTexEnvfv",  void (APIENTRYP )(GLenum,GLenum,GLfloat *),  void (APIENTRYP glGetTexEnvfv)(GLenum target, GLenum pname, GLfloat * params))
  GL_Link_compat(glGetTexEnviv, "glGetTexEnviv",  void (APIENTRYP )(GLenum,GLenum,GLint *),  void (APIENTRYP glGetTexEnviv)(GLenum target, GLenum pname, GLint * params))
  GL_Link_core(glGetTexEnvxv, "glGetTexEnvxv",  void (APIENTRYP )(GLenum,GLenum,GLfixed *),  void (APIENTRYP glGetTexEnvxv)(GLenum target, GLenum pname, GLfixed * params))
  GL_Link_core(glGetTexParameterfv, "glGetTexParameterfv",  void (APIENTRYP )(GLenum,GLenum,GLfloat *),  void (APIENTRYP glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat * params))
  GL_Link_core(glGetTexParameteriv, "glGetTexParameteriv",  void (APIENTRYP )(GLenum,GLenum,GLint *),  void (APIENTRYP glGetTexParameteriv)(GLenum target, GLenum pname, GLint * params))
  GL_Link_core(glGetTexParameterxv, "glGetTexParameterxv",  void (APIENTRYP )(GLenum,GLenum,GLfixed *),  void (APIENTRYP glGetTexParameterxv)(GLenum target, GLenum pname, GLfixed * params))
  GL_Link_core(glHint, "glHint",  void (APIENTRYP )(GLenum,GLenum),  void (APIENTRYP glHint)(GLenum target, GLenum mode))
  GL_Link_core(glIsBuffer, "glIsBuffer", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsBuffer)(GLuint buffer))
  GL_Link_core(glIsEnabled, "glIsEnabled", GLboolean (APIENTRYP )(GLenum), GLboolean (APIENTRYP glIsEnabled)(GLenum cap))
  GL_Link_core(glIsTexture, "glIsTexture", GLboolean (APIENTRYP )(GLuint), GLboolean (APIENTRYP glIsTexture)(GLuint texture))
  GL_Link_compat(glLightModelf, "glLightModelf",  void (APIENTRYP )(GLenum,GLfloat),  void (APIENTRYP glLightModelf)(GLenum pname, GLfloat param))
  GL_Link_compat(glLightModelfv, "glLightModelfv",  void (APIENTRYP )(GLenum,const  GLfloat *),  void (APIENTRYP glLightModelfv)(GLenum pname, const  GLfloat * params))
  GL_Link_core(glLightModelx, "glLightModelx",  void (APIENTRYP )(GLenum,GLfixed),  void (APIENTRYP glLightModelx)(GLenum pname, GLfixed param))
  GL_Link_core(glLightModelxv, "glLightModelxv",  void (APIENTRYP )(GLenum,const  GLfixed *),  void (APIENTRYP glLightModelxv)(GLenum pname, const  GLfixed * param))
  GL_Link_compat(glLightf, "glLightf",  void (APIENTRYP )(GLenum,GLenum,GLfloat),  void (APIENTRYP glLightf)(GLenum light, GLenum pname, GLfloat param))
  GL_Link_compat(glLightfv, "glLightfv",  void (APIENTRYP )(GLenum,GLenum,const  GLfloat *),  void (APIENTRYP glLightfv)(GLenum light, GLenum pname, const  GLfloat * params))
  GL_Link_core(glLightx, "glLightx",  void (APIENTRYP )(GLenum,GLenum,GLfixed),  void (APIENTRYP glLightx)(GLenum light, GLenum pname, GLfixed param))
  GL_Link_core(glLightxv, "glLightxv",  void (APIENTRYP )(GLenum,GLenum,const  GLfixed *),  void (APIENTRYP glLightxv)(GLenum light, GLenum pname, const  GLfixed * params))
  GL_Link_core(glLineWidth, "glLineWidth",  void (APIENTRYP )(GLfloat),  void (APIENTRYP glLineWidth)(GLfloat width))
  GL_Link_core(glLineWidthx, "glLineWidthx",  void (APIENTRYP )(GLfixed),  void (APIENTRYP glLineWidthx)(GLfixed width))
  GL_Link_compat(glLoadIdentity, "glLoadIdentity",  void (APIENTRYP )(),  void (APIENTRYP glLoadIdentity)())
  GL_Link_compat(glLoadMatrixf, "glLoadMatrixf",  void (APIENTRYP )(const  GLfloat *),  void (APIENTRYP glLoadMatrixf)(const  GLfloat * m))
  GL_Link_core(glLoadMatrixx, "glLoadMatrixx",  void (APIENTRYP )(const  GLfixed *),  void (APIENTRYP glLoadMatrixx)(const  GLfixed * m))
  GL_Link_core(glLogicOp, "glLogicOp",  void (APIENTRYP )(GLenum),  void (APIENTRYP glLogicOp)(GLenum opcode))
  GL_Link_compat(glMaterialf, "glMaterialf",  void (APIENTRYP )(GLenum,GLenum,GLfloat),  void (APIENTRYP glMaterialf)(GLenum face, GLenum pname, GLfloat param))
  GL_Link_compat(glMaterialfv, "glMaterialfv",  void (APIENTRYP )(GLenum,GLenum,const  GLfloat *),  void (APIENTRYP glMaterialfv)(GLenum face, GLenum pname, const  GLfloat * params))
  GL_Link_core(glMaterialx, "glMaterialx",  void (APIENTRYP )(GLenum,GLenum,GLfixed),  void (APIENTRYP glMaterialx)(GLenum face, GLenum pname, GLfixed param))
  GL_Link_core(glMaterialxv, "glMaterialxv",  void (APIENTRYP )(GLenum,GLenum,const  GLfixed *),  void (APIENTRYP glMaterialxv)(GLenum face, GLenum pname, const  GLfixed * param))
  GL_Link_compat(glMatrixMode, "glMatrixMode",  void (APIENTRYP )(GLenum),  void (APIENTRYP glMatrixMode)(GLenum mode))
  GL_Link_compat(glMultMatrixf, "glMultMatrixf",  void (APIENTRYP )(const  GLfloat *),  void (APIENTRYP glMultMatrixf)(const  GLfloat * m))
  GL_Link_core(glMultMatrixx, "glMultMatrixx",  void (APIENTRYP )(const  GLfixed *),  void (APIENTRYP glMultMatrixx)(const  GLfixed * m))
  GL_Link_compat(glMultiTexCoord4f, "glMultiTexCoord4f",  void (APIENTRYP )(GLenum,GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glMultiTexCoord4f)(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q))
  GL_Link_core(glMultiTexCoord4x, "glMultiTexCoord4x",  void (APIENTRYP )(GLenum,GLfixed,GLfixed,GLfixed,GLfixed),  void (APIENTRYP glMultiTexCoord4x)(GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q))
  GL_Link_compat(glNormal3f, "glNormal3f",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat),  void (APIENTRYP glNormal3f)(GLfloat nx, GLfloat ny, GLfloat nz))
  GL_Link_core(glNormal3x, "glNormal3x",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed),  void (APIENTRYP glNormal3x)(GLfixed nx, GLfixed ny, GLfixed nz))
  GL_Link_compat(glNormalPointer, "glNormalPointer",  void (APIENTRYP )(GLenum,GLsizei, const void *),  void (APIENTRYP glNormalPointer)(GLenum type, GLsizei stride,  const void * pointer))
  GL_Link_core(glOrthof, "glOrthof",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glOrthof)(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f))
  GL_Link_core(glOrthox, "glOrthox",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed,GLfixed,GLfixed,GLfixed),  void (APIENTRYP glOrthox)(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f))
  GL_Link_core(glPixelStorei, "glPixelStorei",  void (APIENTRYP )(GLenum,GLint),  void (APIENTRYP glPixelStorei)(GLenum pname, GLint param))
  GL_Link_core(glPointParameterf, "glPointParameterf",  void (APIENTRYP )(GLenum,GLfloat),  void (APIENTRYP glPointParameterf)(GLenum pname, GLfloat param))
  GL_Link_core(glPointParameterfv, "glPointParameterfv",  void (APIENTRYP )(GLenum,const  GLfloat *),  void (APIENTRYP glPointParameterfv)(GLenum pname, const  GLfloat * params))
  GL_Link_core(glPointParameterx, "glPointParameterx",  void (APIENTRYP )(GLenum,GLfixed),  void (APIENTRYP glPointParameterx)(GLenum pname, GLfixed param))
  GL_Link_core(glPointParameterxv, "glPointParameterxv",  void (APIENTRYP )(GLenum,const  GLfixed *),  void (APIENTRYP glPointParameterxv)(GLenum pname, const  GLfixed * params))
  GL_Link_core(glPointSize, "glPointSize",  void (APIENTRYP )(GLfloat),  void (APIENTRYP glPointSize)(GLfloat size))
  GL_Link_core(glPointSizex, "glPointSizex",  void (APIENTRYP )(GLfixed),  void (APIENTRYP glPointSizex)(GLfixed size))
  GL_Link_core(glPolygonOffset, "glPolygonOffset",  void (APIENTRYP )(GLfloat,GLfloat),  void (APIENTRYP glPolygonOffset)(GLfloat factor, GLfloat units))
  GL_Link_core(glPolygonOffsetx, "glPolygonOffsetx",  void (APIENTRYP )(GLfixed,GLfixed),  void (APIENTRYP glPolygonOffsetx)(GLfixed factor, GLfixed units))
  GL_Link_compat(glPopMatrix, "glPopMatrix",  void (APIENTRYP )(),  void (APIENTRYP glPopMatrix)())
  GL_Link_compat(glPushMatrix, "glPushMatrix",  void (APIENTRYP )(),  void (APIENTRYP glPushMatrix)())
  GL_Link_core(glReadPixels, "glReadPixels",  void (APIENTRYP )(GLint,GLint,GLsizei,GLsizei,GLenum,GLenum, void *),  void (APIENTRYP glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type,  void * pixels))
  GL_Link_compat(glRotatef, "glRotatef",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat,GLfloat),  void (APIENTRYP glRotatef)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z))
  GL_Link_core(glRotatex, "glRotatex",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed,GLfixed),  void (APIENTRYP glRotatex)(GLfixed angle, GLfixed x, GLfixed y, GLfixed z))
  GL_Link_core(glSampleCoverage, "glSampleCoverage",  void (APIENTRYP )(GLfloat,GLboolean),  void (APIENTRYP glSampleCoverage)(GLfloat value, GLboolean invert))
  GL_Link_core(glSampleCoveragex, "glSampleCoveragex",  void (APIENTRYP )(GLclampx,GLboolean),  void (APIENTRYP glSampleCoveragex)(GLclampx value, GLboolean invert))
  GL_Link_compat(glScalef, "glScalef",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat),  void (APIENTRYP glScalef)(GLfloat x, GLfloat y, GLfloat z))
  GL_Link_core(glScalex, "glScalex",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed),  void (APIENTRYP glScalex)(GLfixed x, GLfixed y, GLfixed z))
  GL_Link_core(glScissor, "glScissor",  void (APIENTRYP )(GLint,GLint,GLsizei,GLsizei),  void (APIENTRYP glScissor)(GLint x, GLint y, GLsizei width, GLsizei height))
  GL_Link_compat(glShadeModel, "glShadeModel",  void (APIENTRYP )(GLenum),  void (APIENTRYP glShadeModel)(GLenum mode))
  GL_Link_core(glStencilFunc, "glStencilFunc",  void (APIENTRYP )(GLenum,GLint,GLuint),  void (APIENTRYP glStencilFunc)(GLenum func, GLint ref, GLuint mask))
  GL_Link_core(glStencilMask, "glStencilMask",  void (APIENTRYP )(GLuint),  void (APIENTRYP glStencilMask)(GLuint mask))
  GL_Link_core(glStencilOp, "glStencilOp",  void (APIENTRYP )(GLenum,GLenum,GLenum),  void (APIENTRYP glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass))
  GL_Link_compat(glTexCoordPointer, "glTexCoordPointer",  void (APIENTRYP )(GLint,GLenum,GLsizei, const void *),  void (APIENTRYP glTexCoordPointer)(GLint size, GLenum type, GLsizei stride,  const void * pointer))
  GL_Link_compat(glTexEnvf, "glTexEnvf",  void (APIENTRYP )(GLenum,GLenum,GLfloat),  void (APIENTRYP glTexEnvf)(GLenum target, GLenum pname, GLfloat param))
  GL_Link_compat(glTexEnvfv, "glTexEnvfv",  void (APIENTRYP )(GLenum,GLenum,const  GLfloat *),  void (APIENTRYP glTexEnvfv)(GLenum target, GLenum pname, const  GLfloat * params))
  GL_Link_compat(glTexEnvi, "glTexEnvi",  void (APIENTRYP )(GLenum,GLenum,GLint),  void (APIENTRYP glTexEnvi)(GLenum target, GLenum pname, GLint param))
  GL_Link_compat(glTexEnviv, "glTexEnviv",  void (APIENTRYP )(GLenum,GLenum,const  GLint *),  void (APIENTRYP glTexEnviv)(GLenum target, GLenum pname, const  GLint * params))
  GL_Link_core(glTexEnvx, "glTexEnvx",  void (APIENTRYP )(GLenum,GLenum,GLfixed),  void (APIENTRYP glTexEnvx)(GLenum target, GLenum pname, GLfixed param))
  GL_Link_core(glTexEnvxv, "glTexEnvxv",  void (APIENTRYP )(GLenum,GLenum,const  GLfixed *),  void (APIENTRYP glTexEnvxv)(GLenum target, GLenum pname, const  GLfixed * params))
  GL_Link_core(glTexImage2D, "glTexImage2D",  void (APIENTRYP )(GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum, const void *),  void (APIENTRYP glTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type,  const void * pixels))
  GL_Link_core(glTexParameterf, "glTexParameterf",  void (APIENTRYP )(GLenum,GLenum,GLfloat),  void (APIENTRYP glTexParameterf)(GLenum target, GLenum pname, GLfloat param))
  GL_Link_core(glTexParameterfv, "glTexParameterfv",  void (APIENTRYP )(GLenum,GLenum,const  GLfloat *),  void (APIENTRYP glTexParameterfv)(GLenum target, GLenum pname, const  GLfloat * params))
  GL_Link_core(glTexParameteri, "glTexParameteri",  void (APIENTRYP )(GLenum,GLenum,GLint),  void (APIENTRYP glTexParameteri)(GLenum target, GLenum pname, GLint param))
  GL_Link_core(glTexParameteriv, "glTexParameteriv",  void (APIENTRYP )(GLenum,GLenum,const  GLint *),  void (APIENTRYP glTexParameteriv)(GLenum target, GLenum pname, const  GLint * params))
  GL_Link_core(glTexParameterx, "glTexParameterx",  void (APIENTRYP )(GLenum,GLenum,GLfixed),  void (APIENTRYP glTexParameterx)(GLenum target, GLenum pname, GLfixed param))
  GL_Link_core(glTexParameterxv, "glTexParameterxv",  void (APIENTRYP )(GLenum,GLenum,const  GLfixed *),  void (APIENTRYP glTexParameterxv)(GLenum target, GLenum pname, const  GLfixed * params))
  GL_Link_core(glTexSubImage2D, "glTexSubImage2D",  void (APIENTRYP )(GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLenum, const void *),  void (APIENTRYP glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type,  const void * pixels))
  GL_Link_compat(glTranslatef, "glTranslatef",  void (APIENTRYP )(GLfloat,GLfloat,GLfloat),  void (APIENTRYP glTranslatef)(GLfloat x, GLfloat y, GLfloat z))
  GL_Link_core(glTranslatex, "glTranslatex",  void (APIENTRYP )(GLfixed,GLfixed,GLfixed),  void (APIENTRYP glTranslatex)(GLfixed x, GLfixed y, GLfixed z))
  GL_Link_compat(glVertexPointer, "glVertexPointer",  void (APIENTRYP )(GLint,GLenum,GLsizei, const void *),  void (APIENTRYP glVertexPointer)(GLint size, GLenum type, GLsizei stride,  const void * pointer))
  GL_Link_core(glViewport, "glViewport",  void (APIENTRYP )(GLint,GLint,GLsizei,GLsizei),  void (APIENTRYP glViewport)(GLint x, GLint y, GLsizei width, GLsizei height))
GL_LinkGroupEnd(base,GL_VERSION_ES_CM_1_0)
