
PLATFORM=$(shell uname).$(shell uname -p)
PLATFORM_ID=linux

SDL_CFLAGS = $(shell sdl2-config --cflags)
SDL_LIBS = $(shell sdl2-config --libs)

BINSUFFIX=
SOLIBSUFFIX=.so
CXXFLAGS += -fPIC -fvisibility=hidden -Werror -D_FILE_OFFSET_BITS=64 -Wl,-z,defs $(SDL_CFLAGS)
STD_LIBS += $(SDL_LIBS) -ljpeg -lpng -lz -lfreetype -lSDL2_ttf

include Makefile.inc
